data_args:
  dataset_name: "actor_movies"    # TODO set dataset name: "country_cities", "artist_songs", "actor_movies"
  cache_dir: None
  add_bos_token: False
  add_eos_token: False

model_args:
  model_name_or_path: "meta-llama/Meta-Llama-3-8B-Instruct"   # TODO set model: "meta-llama/Meta-Llama-3-8B-Instruct", "mistralai/Mistral-7B-Instruct-v0.2"
  config_name: null
  tokenizer_name: null

running_args:
  target_answer_idx: 3    # TODO set answer step: 1, 2, 3
  exp_type: "examine_finegrained_attention_head"   # TODO set experiment type: "decode_attn_mlp_outputs", "analyze_critical_tokens", "examine_finegrained_attention_head"

  # These won't have any effect if exp_type is not "analyze_critical_tokens".
  do_token_lens: True
  do_attention_knockout: True

  batch_size: 1

# Run:
# bash scripts/run_main.sh
